### ISSUE TITLE
Missing Binding

### ISSUE THREAD

**Issue by gargarchit** [lsst-dm/dm_dev_guide#404]
It seems, the function:     
`friend std::ostream& operator<<(std::ostream&, ExampleOne const&);`
is not wrapped in the example given: https://github.com/lsst-dm/dm_dev_guide/blob/master/pybind11/how-to.rst

**Comment by gargarchit** [comment]
@timj @jdswinbank

**Comment by timj** [comment]
Not my bailiwick I'm afraid. @TallJimbo may be able to make a more informed comment.

**Comment by TallJimbo** [comment]
Yeah, looks like it's just an oversight.  Normally we'd recommend https://github.com/lsst/utils/blob/master/include/lsst/utils/python.h#L87 for that.

**Comment by jdswinbank** [comment]
Tracking this internally as [DM-25181](https://jira.lsstcorp.org/browse/DM-25181).

Tangentially, it gives me enormous joy that this “missing binding” issue is a 404.

**Comment by jdswinbank** [comment]
Closed by 9e9af6c2aae915c69c7294830fa49d92449452c1. Thanks for the report, @gargarchit !
