### ISSUE TITLE
Potentially add a step 5 to usdf/onboarding.rst

### ISSUE THREAD

**Issue by davedavemckay** [lsst-dm/dm_dev_guide#702]
Hello,
There was a final step to complete before being able to logon to S3DF, which is documented in this [highlight](https://s3df.slac.stanford.edu/#/accounts-and-access:~:text=Register%20your%20SLAC,about%201%20hour.) in the S3DF docs.
Possibly a useful addition to the onboarding docs.

**Comment by jchiang87** [comment]
Thanks for the suggestion, Dave.  Closed by #703
